### ISSUE TITLE
ASINが１０を超えると処理が止まる

### ISSUE THREAD

**Issue by kyukyunyorituryo** [mjun0812/gatsby-remark-amazon-link#1]
amazon-paapiの仕様でリクエストが最大１０に制限されている。
[$amazon](https://amazon.co.jp/dp/B00000000/?xxxxxx)が１０を超えるとエラーで止まる。

そこで、リンクを１０ごとに分割してリクエストに待ち時間を設定すると、１０を超えても止まらなくなった。

```
    for (let i = 0; i < links.length; i += 10) {
 await sleep(3) 
linker =links.slice(i, i+10)
    await convertLink(linker, accessKey, secretKey, partnerTag, marketplace)
    }
```

**Comment by mjun0812** [comment]
Issueありがとうございます。

https://webservices.amazon.com/paapi5/documentation/troubleshooting/api-rates.html

以上にあるように、確かにRate Limitの考慮を失念していました。
後ほど修正します

**Comment by mjun0812** [comment]
#2 にて修正しました！
